# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Saurabh Mardikar
email: mardikarsaurabh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a software engineer by profession.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mardikar

#######

# Author Settings
author:
  name: Saurabh Mardikar
  # image: '/assets/img/01.jpg'
  job: Full Stack Developer
  bio: |-
    I am passionate about programming and designing distributed systems.
  email: mardikarsaurabh@gmail.com


# Contact links
# contact:
#   - name: Twitter
#     link: https://twitter.com/
#   - name: Facebook
#     link: https://facebook.com/
#   - name: Instagram
#     link: https://instagram.com/


# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: UA-152586164-2 # add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed

#####

# Build settings
remote_theme: artemsheludko/derrick
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll/tagging

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
